// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Balance struct {
	ID      int32
	UserID  int32
	Balance int32
}

type Test struct {
	ID      uuid.UUID
	Name    string
	UserID  uuid.NullUUID
	Balance sql.NullString
}
