// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ecom/internal/controller"
	"ecom/internal/repo"
	"ecom/internal/service"
)

// Injectors from deposit.wire.go:

func InitializeDepositHandler() (*controller.DepositController, error) {
	iCycleRepository := repo.NewCycleRepository()
	iDepositService := service.NewDepositService(iCycleRepository)
	depositController := controller.NewDepositController(iDepositService)
	return depositController, nil
}
