// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ecom/internal/messaging"
)

// Injectors from consume.go:

func InitializeConsumeHandler() (*messaging.ConsumeMessage, error) {
	consumeMessage := messaging.NewConsumeMessage()
	return consumeMessage, nil
}

