// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCurrency = "currency"

// Currency mapped from table <currency>
type Currency struct {
	ID                                int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status                            string `gorm:"column:status;not null;default:draft" json:"status"`
	Name                              string `gorm:"column:name" json:"name"`
	Slug                              string `gorm:"column:slug" json:"slug"`
	IsCryptoToken                     bool   `gorm:"column:is_crypto_token" json:"is_crypto_token"`
	Address                           string `gorm:"column:address" json:"address"`
	Network                           int32  `gorm:"column:network" json:"network"`
	WalletIntegrationsCurrencies      int32  `gorm:"column:wallet_integrations_currencies" json:"wallet_integrations_currencies"`
	WalletIntegrationsInputWithdrawn  int32  `gorm:"column:wallet_integrations_input_withdrawn" json:"wallet_integrations_input_withdrawn"`
	WalletIntegrationsOutputWithdrawn int32  `gorm:"column:wallet_integrations_output_withdrawn" json:"wallet_integrations_output_withdrawn"`
}

// TableName Currency's table name
func (*Currency) TableName() string {
	return TableNameCurrency
}
