// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status             string    `gorm:"column:status;not null;default:draft" json:"status"`
	Sort               int32     `gorm:"column:sort" json:"sort"`
	UserCreated        string    `gorm:"column:user_created" json:"user_created"`
	DateCreated        time.Time `gorm:"column:date_created" json:"date_created"`
	UserUpdated        string    `gorm:"column:user_updated" json:"user_updated"`
	DateUpdated        time.Time `gorm:"column:date_updated" json:"date_updated"`
	Name               string    `gorm:"column:name" json:"name"`
	Slug               string    `gorm:"column:slug" json:"slug"`
	Publickey          string    `gorm:"column:publickey" json:"publickey"`
	WalletIntegrations int32     `gorm:"column:wallet_integrations" json:"wallet_integrations"`
	PlatformConfigs    int32     `gorm:"column:platform_configs" json:"platform_configs"`
	WalletFees         int32     `gorm:"column:wallet_fees" json:"wallet_fees"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
