// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTransactionType = "transaction_type"

// TransactionType mapped from table <transaction_type>
type TransactionType struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status      string `gorm:"column:status;not null;default:draft" json:"status"`
	Name        string `gorm:"column:name" json:"name"`
	Slug        string `gorm:"column:slug" json:"slug"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName TransactionType's table name
func (*TransactionType) TableName() string {
	return TableNameTransactionType
}
