// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	Details         json.RawMessage `gorm:"column:details" json:"details"`
	Amount          float64         `gorm:"column:amount" json:"amount"`
	RateUsd         float64         `gorm:"column:rate_usd" json:"rate_usd"`
	ID              string          `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID          string    `gorm:"column:user_id" json:"user_id"`
	DateCreated     time.Time `gorm:"column:date_created;default:now()" json:"date_created"`
	DateUpdated     time.Time `gorm:"column:date_updated" json:"date_updated"`
	TransactionType string    `gorm:"column:transaction_type" json:"transaction_type"`
	Platform        string    `gorm:"column:platform" json:"platform"`
	Icon            string    `gorm:"column:icon" json:"icon"`
	Code            string    `gorm:"column:code" json:"code"`
	Status          string    `gorm:"column:status" json:"status"`
	Description     string    `gorm:"column:description" json:"description"`
	Currency        string    `gorm:"column:currency" json:"currency"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
