// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	FirstName   string    `gorm:"column:first_name" json:"first_name"`
	ProviderKey string    `gorm:"column:provider_key" json:"provider_key"`
	NickName    string    `gorm:"column:nick_name" json:"nick_name"`
	LastName    string    `gorm:"column:last_name" json:"last_name"`
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	DateCreated time.Time `gorm:"column:date_created;default:now()" json:"date_created"`
	DateUpdated time.Time `gorm:"column:date_updated" json:"date_updated"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
