// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWallet = "wallet"

// Wallet mapped from table <wallet>
type Wallet struct {
	IsNew          bool      `gorm:"column:is_new;default:true" json:"is_new"`
	ID             string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID         string    `gorm:"column:user_id" json:"user_id"`
	DateCreated    time.Time `gorm:"column:date_created;default:now()" json:"date_created"`
	DateUpdated    time.Time `gorm:"column:date_updated" json:"date_updated"`
	Balance        string    `gorm:"column:balance" json:"balance"`
	ProviderKey    string    `gorm:"column:provider_key" json:"provider_key"`
	AmountInterest string    `gorm:"column:amount_interest" json:"amount_interest"`
	TimeDeposit    string    `gorm:"column:time_deposit" json:"time_deposit"`
	LastTimeUpdate string    `gorm:"column:last_time_update" json:"last_time_update"`
	Currency       string    `gorm:"column:currency" json:"currency"`
}

// TableName Wallet's table name
func (*Wallet) TableName() string {
	return TableNameWallet
}
