// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWalletIntegration = "wallet_integrations"

// WalletIntegration mapped from table <wallet_integrations>
type WalletIntegration struct {
	ID                         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status                     string    `gorm:"column:status;not null;default:draft" json:"status"`
	Sort                       int32     `gorm:"column:sort" json:"sort"`
	UserCreated                string    `gorm:"column:user_created" json:"user_created"`
	DateCreated                time.Time `gorm:"column:date_created" json:"date_created"`
	UserUpdated                string    `gorm:"column:user_updated" json:"user_updated"`
	DateUpdated                time.Time `gorm:"column:date_updated" json:"date_updated"`
	Key                        string    `gorm:"column:key;default:NULL" json:"key"`
	InterestDefault            int32     `gorm:"column:interest_default" json:"interest_default"`
	InterestDetail             string    `gorm:"column:interest_detail" json:"interest_detail"`
	UrgentWithdrawalFeePercent float64   `gorm:"column:urgent_withdrawal_fee_percent" json:"urgent_withdrawal_fee_percent"`
	DepositLockTime            int32     `gorm:"column:deposit_lock_time" json:"deposit_lock_time"`
	FreeWithdrawalsCount       int32     `gorm:"column:free_withdrawals_count" json:"free_withdrawals_count"`
	FreeWithdrawalLimit        float64   `gorm:"column:free_withdrawal_limit" json:"free_withdrawal_limit"`
	CurrencyMergeEnabled       bool      `gorm:"column:currency_merge_enabled" json:"currency_merge_enabled"`
	FeeSetting                 string    `gorm:"column:fee_setting" json:"fee_setting"`
	IsAutoTakeProfit           bool      `gorm:"column:is_auto_take_profit;default:true" json:"is_auto_take_profit"`
	Cronjob                    string    `gorm:"column:cronjob" json:"cronjob"`
	ProfitTakingCycle          int32     `gorm:"column:profit_taking_cycle" json:"profit_taking_cycle"`
	Name                       string    `gorm:"column:name" json:"name"`
	MinDeposit                 float64   `gorm:"column:min_deposit" json:"min_deposit"`
	MinWithdrawn               float64   `gorm:"column:min_withdrawn" json:"min_withdrawn"`
	MaxWithdrawn               float64   `gorm:"column:max_withdrawn" json:"max_withdrawn"`
}

// TableName WalletIntegration's table name
func (*WalletIntegration) TableName() string {
	return TableNameWalletIntegration
}
