// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWalletIntegrationCurrency = "wallet_integration_currencies"

// WalletIntegrationCurrency mapped from table <wallet_integration_currencies>
type WalletIntegrationCurrency struct {
	ID                   int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status               string    `gorm:"column:status;not null;default:draft" json:"status"`
	Sort                 int32     `gorm:"column:sort" json:"sort"`
	UserCreated          string    `gorm:"column:user_created" json:"user_created"`
	DateCreated          time.Time `gorm:"column:date_created" json:"date_created"`
	UserUpdated          string    `gorm:"column:user_updated" json:"user_updated"`
	DateUpdated          time.Time `gorm:"column:date_updated" json:"date_updated"`
	WalletIntegrationsID int32     `gorm:"column:wallet_integrations_id" json:"wallet_integrations_id"`
	CurrencyID           int32     `gorm:"column:currency_id" json:"currency_id"`
	Type                 string    `gorm:"column:type" json:"type"`
	Currency             Currency  `gorm:"foreignKey:CurrencyID" json:"currency"`
}

// TableName WalletIntegrationCurrency's table name
func (*WalletIntegrationCurrency) TableName() string {
	return TableNameWalletIntegrationCurrency
}
