// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebhookLog = "webhook_logs"

// WebhookLog mapped from table <webhook_logs>
type WebhookLog struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status          string    `gorm:"column:status;not null;default:success" json:"status"`
	Sort            int32     `gorm:"column:sort" json:"sort"`
	DateCreated     time.Time `gorm:"column:date_created" json:"date_created"`
	DateUpdated     time.Time `gorm:"column:date_updated" json:"date_updated"`
	URL             string    `gorm:"column:url" json:"url"`
	TransactionCode string    `gorm:"column:transaction_code" json:"transaction_code"`
}

// TableName WebhookLog's table name
func (*WebhookLog) TableName() string {
	return TableNameWebhookLog
}
